"""
build_field_data.py  -  the bridge from the dataset to the interactive map.

Reads the two cleaned datasets (direct and indirect free kicks), bins the
attacking half into a grid, and writes app/field_stats.json. The web app
(app/app.js) loads that file and fills the tile: when you click a spot, it
looks up the grid cell and shows the free-kick success rate, shot/goal counts,
and the nearest scorer from that area.

Each cell also carries a direct/indirect breakdown, so the heatmap can shade
the two free-kick types separately.

Run it whenever the data changes:

    python src/build_field_data.py

Grid frame matches app.js: StatsBomb 120x80 pitch, attacking half is x 60-120.
Rows without x/y coordinates are skipped because the map is coordinate-based.
"""
import json
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
# The cleaned data ships as one file per free-kick type.
SOURCES = {
    "direct": os.path.join(DATA, "freekicks_direct_only.csv"),
    "indirect": os.path.join(DATA, "freekicks_indirect_only.csv"),
}
OUT = os.path.join(ROOT, "app", "field_stats.json")
STANDALONE = os.path.join(ROOT, "freekick_map.html")   # single double-clickable file

BIN = 5            # cell size in yards
X_MIN, X_MAX = 60, 120
Y_MIN, Y_MAX = 0, 80


def is_real_name(v):
    """Guard against blank or numeric-id player values."""
    if pd.isna(v):
        return False
    try:
        float(v)          # numeric -> an id, not a usable name
        return False
    except (ValueError, TypeError):
        return True


def load_sources():
    """Load the direct and indirect files into one frame tagged by type."""
    frames = []
    for fk_type, path in SOURCES.items():
        if not os.path.exists(path):
            raise SystemExit(
                f"Missing {os.path.relpath(path, ROOT)}. Expected the cleaned "
                f"direct/indirect free-kick CSVs in data/."
            )
        part = pd.read_csv(path, low_memory=False, encoding="utf-8")
        part["fk_type"] = fk_type
        frames.append(part)
        print(f"  loaded {os.path.basename(path)}: {len(part)} rows")
    return pd.concat(frames, ignore_index=True)


def summarize(grp):
    shots = len(grp)
    goals = int(grp["is_goal"].sum())
    return {"shots": shots, "goals": goals,
            "rate": round(goals / shots, 4) if shots else 0.0}


def main():
    df = load_sources()
    df = df.dropna(subset=["location_x", "location_y"])
    df = df[(df["location_x"] >= X_MIN) & (df["location_x"] <= X_MAX)]

    df["ix"] = ((df["location_x"] - X_MIN) // BIN).astype(int)
    df["iy"] = ((df["location_y"] - Y_MIN) // BIN).astype(int)

    cells = {}
    for (ix, iy), grp in df.groupby(["ix", "iy"]):
        cx = X_MIN + (ix + 0.5) * BIN
        cy = Y_MIN + (iy + 0.5) * BIN

        nearest = None
        scorers = grp[(grp["is_goal"] == 1) & grp["player"].map(is_real_name)]
        if len(scorers):
            d = (scorers["location_x"] - cx) ** 2 + (scorers["location_y"] - cy) ** 2
            r = scorers.loc[d.idxmin()]
            nearest = {
                "player": str(r["player"]),
                "x": round(float(r["location_x"]), 1),
                "y": round(float(r["location_y"]), 1),
                "competition": str(r.get("competition", "")),
            }

        cell = summarize(grp)
        cell["nearest_scorer"] = nearest
        # per-type breakdown so the heatmap can show direct and indirect apart
        for fk_type in SOURCES:
            sub = grp[grp["fk_type"] == fk_type]
            cell[fk_type] = summarize(sub) if len(sub) else None
        cells[f"{ix}_{iy}"] = cell

    totals = {t: summarize(df[df["fk_type"] == t]) for t in SOURCES}
    payload = {
        "meta": {
            "generated": pd.Timestamp.now("UTC").isoformat(),
            "source_rows": int(len(df)),
            "totals": totals,
            "note": ("Generated by src/build_field_data.py from "
                     "data/freekicks_direct_only.csv and data/freekicks_indirect_only.csv"),
        },
        "bin_size": BIN,
        "x_min": X_MIN, "x_max": X_MAX,
        "y_min": Y_MIN, "y_max": Y_MAX,
        "cells": cells,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f)
    print(f"Wrote {OUT}: {len(cells)} cells from {len(df)} located free-kick shots.")
    for t, s in totals.items():
        print(f"  {t:9s} {s['shots']:6d} shots  {s['goals']:5d} goals  "
              f"{100 * s['rate']:.2f}%")

    inject_standalone(payload)


def inject_standalone(payload):
    """Bake the data into freekick_map.html so it works by double-clicking.

    A browser opening a file:// page is not allowed to fetch a separate JSON
    file, so the single-file version carries its data inline. We swap the line
    tagged with the FIELD_DATA marker.
    """
    if not os.path.exists(STANDALONE):
        return
    slim = {
        "bin_size": payload["bin_size"],
        "x_min": payload["x_min"], "x_max": payload["x_max"],
        "y_min": payload["y_min"], "y_max": payload["y_max"],
        "cells": payload["cells"],
    }
    # ensure_ascii=True keeps accented player names as \uXXXX escapes, so the
    # file survives being emailed, zipped, or re-saved on any machine.
    new_line = ("const FIELD_DATA = "
                + json.dumps(slim, ensure_ascii=True)
                + "; /*FIELD_DATA*/")

    with open(STANDALONE, "r", encoding="utf-8") as f:
        lines = f.readlines()
    for i, line in enumerate(lines):
        if "/*FIELD_DATA*/" in line:
            lines[i] = new_line + "\n"
            break
    else:
        print("  (marker not found in freekick_map.html, skipped)")
        return
    with open(STANDALONE, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"Wrote {STANDALONE}: data baked in, open it by double-clicking.")


if __name__ == "__main__":
    main()
