"""
build_field_data.py  -  the bridge from the dataset to the interactive map.

Reads data/freekicks_all.csv, bins the attacking half into a grid, and writes
app/field_stats.json. The web app (app/app.js) loads that file and fills the
tile: when you click a spot, it looks up the grid cell and shows the free-kick
success rate, shot/goal counts, and the nearest scorer from that area.

Run it whenever the data changes:

    python src/build_field_data.py

Grid frame matches app.js: StatsBomb 120x80 pitch, attacking half is x 60-120.
Rows without x/y coordinates (e.g. the Football Events source) are skipped
because the map is coordinate-based.
"""
import json
import os
import math

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV = os.path.join(ROOT, "data", "freekicks_all.csv")
OUT = os.path.join(ROOT, "app", "field_stats.json")
STANDALONE = os.path.join(ROOT, "freekick_map.html")   # single double-clickable file

BIN = 5            # cell size in yards
X_MIN, X_MAX = 60, 120
Y_MIN, Y_MAX = 0, 80


def is_real_name(v):
    """StatsBomb rows carry real names; HuggingFace rows are anonymized numbers."""
    if pd.isna(v):
        return False
    try:
        float(v)          # numeric -> anonymized id, not a usable name
        return False
    except (ValueError, TypeError):
        return True


def main():
    df = pd.read_csv(CSV, low_memory=False)
    df = df.dropna(subset=["location_x", "location_y"])
    df = df[(df["location_x"] >= X_MIN) & (df["location_x"] <= X_MAX)]

    df["ix"] = ((df["location_x"] - X_MIN) // BIN).astype(int)
    df["iy"] = ((df["location_y"] - Y_MIN) // BIN).astype(int)

    cells = {}
    for (ix, iy), grp in df.groupby(["ix", "iy"]):
        shots = len(grp)
        goals = int(grp["is_goal"].sum())
        cx = X_MIN + (ix + 0.5) * BIN
        cy = Y_MIN + (iy + 0.5) * BIN

        nearest = None
        scorers = grp[(grp["is_goal"] == 1) & grp["player"].map(is_real_name)]
        if len(scorers):
            d = (scorers["location_x"] - cx) ** 2 + (scorers["location_y"] - cy) ** 2
            r = scorers.loc[d.idxmin()]
            nearest = {
                "player": str(r["player"]),
                "x": round(float(r["location_x"]), 1),
                "y": round(float(r["location_y"]), 1),
                "competition": str(r.get("competition", "")),
            }

        cells[f"{ix}_{iy}"] = {
            "shots": shots,
            "goals": goals,
            "rate": round(goals / shots, 4),
            "nearest_scorer": nearest,
        }

    payload = {
        "meta": {
            "generated": pd.Timestamp.now("UTC").isoformat(),
            "source_rows": int(len(df)),
            "note": "Generated by src/build_field_data.py from data/freekicks_all.csv",
        },
        "bin_size": BIN,
        "x_min": X_MIN, "x_max": X_MAX,
        "y_min": Y_MIN, "y_max": Y_MAX,
        "cells": cells,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f)
    print(f"Wrote {OUT}: {len(cells)} cells from {len(df)} located free-kick shots.")

    inject_standalone(payload)


def inject_standalone(payload):
    """Bake the data into freekick_map.html so it works by double-clicking.

    A browser opening a file:// page is not allowed to fetch a separate JSON
    file, so the single-file version carries its data inline. We swap the line
    tagged with the FIELD_DATA marker.
    """
    if not os.path.exists(STANDALONE):
        return
    slim = {
        "bin_size": payload["bin_size"],
        "x_min": payload["x_min"], "x_max": payload["x_max"],
        "y_min": payload["y_min"], "y_max": payload["y_max"],
        "cells": payload["cells"],
    }
    # ensure_ascii=True keeps accented player names as \uXXXX escapes, so the
    # file survives being emailed, zipped, or re-saved on any machine.
    new_line = ("const FIELD_DATA = "
                + json.dumps(slim, ensure_ascii=True)
                + "; /*FIELD_DATA*/")

    with open(STANDALONE, "r", encoding="utf-8") as f:
        lines = f.readlines()
    for i, line in enumerate(lines):
        if "/*FIELD_DATA*/" in line:
            lines[i] = new_line + "\n"
            break
    else:
        print("  (marker not found in freekick_map.html, skipped)")
        return
    with open(STANDALONE, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"Wrote {STANDALONE}: data baked in, open it by double-clicking.")


if __name__ == "__main__":
    main()
